global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'backend'
    static_configs:
      - targets: ['backend:4000']
        labels:
          service: 'backend'

  - job_name: 'task-orchestrator'
    static_configs:
      - targets: ['task-orchestrator:5000']
        labels:
          service: 'orchestrator'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
        labels:
          service: 'prometheus'
